"""Initial migration

Revision ID: d0a2d70fc984
Revises: 
Create Date: 2025-11-07 00:49:46.959301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd0a2d70fc984'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop tables in correct order: drop dependent tables first
    # moves has foreign keys to both games and players, so drop it first
    # Indexes will be automatically dropped when tables are dropped
    
    # Drop moves table first (it has foreign keys to games and players)
    op.execute('DROP TABLE IF EXISTS moves CASCADE')
    
    # Drop games table (no longer referenced by moves)
    op.execute('DROP TABLE IF EXISTS games CASCADE')
    
    # Drop players table (no longer referenced by moves)
    op.execute('DROP TABLE IF EXISTS players CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moves',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('game_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('player_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('move_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('move_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name='moves_game_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name='moves_player_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='moves_pkey')
    )
    op.create_index('idx_moves_player_id', 'moves', ['player_id'], unique=False)
    op.create_index('idx_moves_game_id', 'moves', ['game_id'], unique=False)
    op.create_table('games',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'waiting'::character varying"), autoincrement=False, nullable=True),
    sa.Column('player1_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('player2_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('current_turn', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('game_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='games_pkey')
    )
    op.create_index('idx_games_status', 'games', ['status'], unique=False)
    op.create_index('idx_games_players', 'games', ['player1_id', 'player2_id'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('rating', sa.INTEGER(), server_default=sa.text('1200'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='players_pkey'),
    sa.UniqueConstraint('email', name='players_email_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('username', name='players_username_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
