apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
stringData:
  POSTGRES_USER: mainuser
  POSTGRES_ROOT_PASSWORD: PassThePerf%5^6
  POSTGRES_PASSWORD: Aauth123
  JWT_SECRET: superstron$g$ecret$d^3dtsty7rhdfh2321fdsgdfghg)%_$
type: Opaque